version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - ENV=dev

    volumes:
      - .:/app
    networks:
      - my_network
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./vol1:/var/lib/postgresql/data
      - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
    networks:
      - my_network
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - my_network
    depends_on:
      - db
volumes:
  vol1:
  pgadmin:
networks:
  my_network:
    driver: bridge